### ISSUE TITLE
Game system

### ISSUE THREAD

**Issue by Tobias-Schwarze** [kasperbuurDK/DonGun#64]
@kasperbuurDK @kasperbuur 
- [x] str: damage modifier, e.g. from str[0-max] rand + d10 from player.
- [x] dex: hit modifier, e.g. from dex[0-max] rand + d20 from player.
- [x] con: health modifier, e.g. from con[max].
- [x] int: sight modifier,  e.g. from int[max]/3 + 5
- [x] wis: ressource modifier, e.g. from wis[max]*2
- [x] cha: interaction/help others modifier, e.g. from wis[max].
- [ ]

**Comment by kasperbuurDK** [comment]
healthMax is made to be 50 + 2*con
